apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksAllowedCapabilities
metadata:
  name: allowed-capabilities
  annotations:
    description: "Controls allowed container capabilities and required capability drops (CIS EKS 4.5.2)"
    version: "{{ .Values.constraints.eksallowedcapabilities.version }}" 
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.eksallowedcapabilities.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
  parameters:
    {{- $allowedCapabilities := $customExemptions.allowedCapabilities | default list }}
    allowedCapabilities: {{ toYaml $allowedCapabilities | nindent 6 }}
    {{- $requiredDropCapabilities := $customExemptions.requiredDropCapabilities | default list }}
    requiredDropCapabilities: {{ toYaml $requiredDropCapabilities | nindent 6 }}
    {{- $excludedContainers := $customExemptions.excludedContainers | default list }}
    excludedContainers: {{ toYaml $excludedContainers | nindent 6 }}
    {{- $excludedImages := $customExemptions.excludedImages | default list }}
    excludedImages: {{ toYaml $excludedImages | nindent 6 }}
