apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sBlockDefaultNamespaceEffect
metadata:
  name: block-default-namespace
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod", "Service", "ConfigMap", "Secret", "ServiceAccount"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.eksblockdefaultnamespaceeffect.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
    labelSelector:
      {{- $baselineLabels := .Values.baselines.labelSelector | default dict }}
      {{- $customLabels := $customExemptions.labelSelector | default dict }}
      {{- if or $baselineLabels.matchLabels $customLabels.matchLabels }}
      matchLabels:
        {{- $baselineMatchLabels := $baselineLabels.matchLabels | default dict }}
        {{- $customMatchLabels := $customLabels.matchLabels | default dict }}
        {{- $combinedMatchLabels := merge $baselineMatchLabels $customMatchLabels }}
        {{ toYaml $combinedMatchLabels | nindent 8 }}
      {{- end }}
