apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksBlockAutomountToken
metadata:
  name: disallow-automount-api-token
  annotations:
    description: "Prevents pods from automatically mounting service account tokens (CIS EKS 4.5.2)"
    version: "{{ .Values.constraints.eksblockautomounttoken.version }}"
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.eksblockautomounttoken.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
  parameters:
    {{- $excludedImages := $customExemptions.excludedImages | default list }}
    excludedImages: {{ toYaml $excludedImages | nindent 6 }}
