apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksBlockDefaultNamespace
metadata:
  name: block-default-namespace
  annotations:
    description: "Prevents resources from being created in the default namespace (CIS EKS 4.5.3)"
    version: "{{ .Values.constraints.eksblockdefaultnamespace.version }}"
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod", "Service", "ConfigMap", "Secret", "ServiceAccount"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.eksblockdefaultnamespace.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
    labelSelector:
      matchExpressions:
        - key: "exempted"
          operator: NotIn
          values:
            - "{{ .Values.constraints.eksblockdefaultnamespace.exemptions.labelSelector.matchLabels.exempted | default "" }}"
  parameters:
    {{- $allowedResources := $customExemptions.allowedResources | default list }}
    allowedResources: {{ toYaml $allowedResources | nindent 6 }}