apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksContainerNoPrivilege
metadata:
  name: disallow-privileged-containers
  annotations:
    description: "Prevents privileged container creation in EKS clusters (CIS EKS 5.2.1)"
    version: "{{ .Values.constraints.ekscontainernoprivilege.version }}"
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.ekscontainernoprivilege.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
  parameters:
    {{- $excludedContainers := $customExemptions.excludedContainers | default list }}
    excludedContainers: {{ toYaml $excludedContainers | nindent 6 }}
    {{- $excludedImages := $customExemptions.excludedImages | default list }}
    excludedImages: {{ toYaml $excludedImages | nindent 6 }}
