apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksEnforceSecretAccess
metadata:
  name: enforce-secret-access
  annotations:
    description: "Minimizes access to secrets in the Kubernetes cluster (CIS EKS 4.1.2)"
    version: "{{ .Values.constraints.eksenforcesecretaccess.version }}"
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["Role", "ClusterRole"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.eksenforcesecretaccess.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
    labelSelector:
      {{- $baselineLabels := .Values.baselines.labelSelector | default dict }}
      {{- $customLabels := $customExemptions.labelSelector | default dict }}
      {{- if or $baselineLabels.matchLabels $customLabels.matchLabels }}
      matchLabels:
        {{- $baselineMatchLabels := $baselineLabels.matchLabels | default dict }}
        {{- $customMatchLabels := $customLabels.matchLabels | default dict }}
        {{- $combinedMatchLabels := merge $baselineMatchLabels $customMatchLabels }}
        {{ toYaml $combinedMatchLabels | nindent 8 }}
      matchExpressions:
        {{- $baselineExpressions := .Values.baselines.labelSelector.matchExpressions | default list }}
        {{- $customExpressions := .Values.constraints.eksallowedcapabilities.exemptions.labelSelector.matchExpressions | default list }}
        {{ toYaml (concat $baselineExpressions $customExpressions) | nindent 8 }}
      {{- end }}
  parameters:
    {{- $baselineAllowedRoles := .Values.baselines.whitelistedRoles | default list }}
    {{- $allowedRoles := $customExemptions.allowedRoles | default list }}
    allowedRoles: {{ concat $baselineAllowedRoles $allowedRoles | toYaml | nindent 6 }}