apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksForbiddenSysctl
metadata:
  name: forbidden-sysctls
  annotations:
    description: "Prevents pods from using unsafe sysctls (CIS EKS 4.5.2)"
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.eksforbiddensysctl.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
    labelSelector:
      {{- $baselineLabels := .Values.baselines.labelSelector | default dict }}
      {{- $customLabels := $customExemptions.labelSelector | default dict }}
      {{- if or $baselineLabels.matchLabels $customLabels.matchLabels }}
      matchLabels:
        {{- $baselineMatchLabels := $baselineLabels.matchLabels | default dict }}
        {{- $customMatchLabels := $customLabels.matchLabels | default dict }}
        {{- $combinedMatchLabels := merge $baselineMatchLabels $customMatchLabels }}
        {{ toYaml $combinedMatchLabels | nindent 8 }}
      {{- end }}
  parameters:
    forbiddenSysctls:
      - "*"
      - "kernel."
    {{- $excludedImages := $customExemptions.excludedImages | default list }}
    excludedImages: {{ toYaml $excludedImages | nindent 6 }}
    {{- $allowedSysctls := $customExemptions.allowedSysctls | default list }}
    allowedSysctls: {{ toYaml $allowedSysctls | nindent 6 }}