apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksLimitSensitiveVerbs
metadata:
  name: limit-sensitive-verbs
  annotations:
    description: "Limits use of bind, impersonate and escalate permissions in RBAC roles (CIS EKS 4.1.8)"
    version: "{{ .Values.constraints.ekslimitsensitiveverbs.version }}"
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: ["rbac.authorization.k8s.io"]
        kinds: ["Role", "ClusterRole"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.ekslimitsensitiveverbs.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
    labelSelector:
      matchExpressions:
        - key: "exempted"
          operator: NotIn
          values:
            - "{{ .Values.constraints.ekslimitsensitiveverbs.exemptions.labelSelector.matchLabels.exempted | default "" }}"
  parameters:
    {{- $baselineAllowedRoles := .Values.baselines.whitelistedRoles | default list }}
    {{- $allowedRoles := $customExemptions.allowedRoles | default list }}
    allowedRoles: {{ concat $baselineAllowedRoles $allowedRoles | toYaml | nindent 6 }}