apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksMountedSecrets
metadata:
  name: eksmountedsecrets
  annotations:
    description: "Prevents using secrets as environment variables (CIS EKS 4.4.1)"
    version: "{{ .Values.constraints.eksmountedsecrets.version }}"
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.eksmountedsecrets.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
    labelSelector:
      matchExpressions:
        - key: "exempted"
          operator: NotIn
          values:
            - "{{ .Values.constraints.eksmountedsecrets.exemptions.labelSelector.matchLabels.exempted | default "" }}"
  parameters:
    {{- $excludedImages := $customExemptions.excludedImages | default list }}
    excludedImages: {{ toYaml $excludedImages | nindent 6 }}
    {{- $allowedSecrets := $customExemptions.allowedSecrets | default list }}
    allowedSecrets: {{ toYaml $allowedSecrets | nindent 6 }}