apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksNetworkPolicyExists
metadata:
  name: ensure-network-policy
  annotations:
    description: "Ensures namespaces have a NetworkPolicy defined (CIS EKS 4.3.2, 5.4.4)"
    version: "{{ .Values.constraints.eksnetworkpolicyexists.version }}"
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.eksnetworkpolicyexists.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
  parameters:
    exemptWithAnnotation: "network.policy.skip/servicemesh"
    exemptWithLabel: "network.policy.skip"