apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksPspHostNamespace
metadata:
  name: psp-host-namespace
  annotations:
    description: "Prevents containers from sharing host namespaces (CIS EKS 4.2.2, 4.2.3, 4.2.4)"
    version: "{{ .Values.constraints.ekspsphostnamespace.version }}"
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.ekspsphostnamespace.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
  parameters:
    {{- $excludedImages := $customExemptions.excludedImages | default list }}
    excludedImages: {{ toYaml $excludedImages | nindent 6 }}