apiVersion: constraints.gatekeeper.sh/v1beta1
kind: EksReadOnlyFilesystem
metadata:
  name: read-only-root-filesystem
  annotations:
    description: "Enforces read-only root filesystem for containers (CIS EKS 4.5.2)"
    version: "{{ .Values.constraints.eksreadonlyfilesystem.version }}"
spec:
  enforcementAction: {{ .Values.constraints.enforcementAction | default "deny" }}
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    {{- $baselineNamespaces := .Values.baselines.excludedNamespaces | default list }}
    {{- $customExemptions := .Values.constraints.eksreadonlyfilesystem.exemptions | default dict }}
    {{- $customNamespaces := $customExemptions.excludedNamespaces | default list }}
    excludedNamespaces: {{ concat $baselineNamespaces $customNamespaces | toYaml | nindent 6 }}
  parameters:
    {{- $excludedContainers := $customExemptions.excludedContainers | default list }}
    excludedContainers: {{ toYaml $excludedContainers | nindent 6 }}
    {{- $excludedImages := $customExemptions.excludedImages | default list }}
    excludedImages: {{ toYaml $excludedImages | nindent 6 }}