apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  labels:
    app: {{ include "my-network-policies.name" . }}
spec:
  podSelector: {{- toYaml .Values.namespaceSelector | nindent 2 }}
  policyTypes:
    - Ingress
  ingress:
    - {}
