apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: eksallowedimages
spec:
  crd:
    spec:
      names:
        kind: K8sAllowedImages
      validation:
        openAPIV3Schema:
          properties:
            imageRegex:
              type: string
            excludedContainers:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sallowedimages

        violation[{"msg": msg}] {
          container := input_containers[_]
          not input_container_excluded(container.name)
          not regex.match(input.parameters.imageRegex, container.image)
          msg := sprintf("Image <%v> for container <%v> does not match allowed registry pattern.", [container.image, container.name])
        }

        input_containers[c] {
          c := input.review.object.spec.containers[_]
        }

        input_container_excluded(name) {
          name == input.parameters.excludedContainers[_]
        }
