baselines:
  excludedNamespaces:
  - kube-system
  - amazon-cloudwatch
  - gatekeeper-system
  - amazon-guardduty

  whitelistedRoles:
  - "admin"
  - "system:*"
  - "eks:*"
  - "cluster-admin"
  - "gatekeeper-manager-role"
  - "system:masters"
  - "system:controller:clusterrole-aggregation-controller"
  - "system:controller:expand-controller"
  - "system:controller:generic-garbage-collector"
  - "system:controller:namespace-controller"
  - "system:controller:persistent-volume-binder"
  - "system:kube-controller-manager"

  labelSelector:
    matchLabels: {}
    matchExpressions: []

constraints:
  enforcementAction: []

  eksallowedcapabilities:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      allowedCapabilities: []
      requiredDropCapabilities: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksallowedimages:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      allowedRegistries: []
      requireDigests: true
      allowedPullPolicies: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksnoprivilegeescalation:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksenforceprobes:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      enforceProbes: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksminimisewildcard:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksblockdefaultnamespace:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedResources: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksblockautomounttoken:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  ekscontainernoprivilege:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksreadonlyfilesystem:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  ekslimitsensitiveverbs:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksenforcesecretaccess:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksforbiddensysctl:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedSysctls:
      - "net.ipv4.ip_local_port_range"
      - "net.ipv4.tcp_syncookies"
      - "net.ipv4.ping_group_range"
      - "net.core.somaxconn"
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksmountedsecrets:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedSecrets: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksnetworkpolicyexists:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  ekspsphostnamespace:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  ekspsphostfilesystem:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedHostPaths: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksadminaccess:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksrestrictdefaultsa:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksresourcelimits:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []
