baselines:
  excludedNamespaces:
  - kube-system
  - amazon-cloudwatch
  - gatekeeper-system
  - amazon-guardduty

  whitelistedRoles:
  - "admin"
  - "system:*"
  - "eks:*"
  - "cluster-admin"
  - "gatekeeper-manager-role"
  - "system:masters"
  - "system:controller:clusterrole-aggregation-controller"
  - "system:controller:expand-controller"
  - "system:controller:generic-garbage-collector"
  - "system:controller:namespace-controller"
  - "system:controller:persistent-volume-binder"
  - "system:kube-controller-manager"

  labelSelector:
    matchLabels: {}
    matchExpressions: []

constraints:
  enforcementAction: []

  eksallowedcapabilities:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      allowedCapabilities: []
      requiredDropCapabilities: []
      labelSelector:
        matchLabels: {}

  eksallowedimages:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      allowedRegistries: []
      requireDigests: true
      allowedPullPolicies: []
      labelSelector:
        matchLabels: {}

  eksnoprivilegeescalation:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      labelSelector:
        matchLabels: {}

  eksenforceprobes:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      enforceProbes: []
      labelSelector:
        matchLabels: {}

  eksminimisewildcard:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []
      labelSelector:
        matchLabels: {}

  eksblockdefaultnamespace:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedResources: []
      labelSelector:
        matchLabels: {}

  eksblockautomounttoken:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      labelSelector:
        matchLabels: {}

  ekscontainernoprivilege:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      labelSelector:
        matchLabels: {}

  eksreadonlyfilesystem:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      labelSelector:
        matchLabels: {}

  ekslimitsensitiveverbs:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []
      labelSelector:
        matchLabels: {}

  eksenforcesecretaccess:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []
      labelSelector:
        matchLabels: {}

  eksforbiddensysctl:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedSysctls:
      - "net.ipv4.ip_local_port_range"
      - "net.ipv4.tcp_syncookies"
      - "net.ipv4.ping_group_range"
      - "net.core.somaxconn"
      labelSelector:
        matchLabels: {}

  eksmountedsecrets:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedSecrets: []
      labelSelector:
        matchLabels: {}

  eksnetworkpolicyexists:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      labelSelector:
        matchLabels: {}

  ekspsphostnamespace:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      labelSelector:
        matchLabels: {}

  ekspsphostfilesystem:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedHostPaths: []
      labelSelector:
        matchLabels: {}

  eksadminaccess:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []
      labelSelector:
        matchLabels: {}

  eksrestrictdefaultsa:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      labelSelector:
        matchLabels: {}

  eksresourcelimits:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
