baselines:
  excludedNamespaces:
  - kube-system
  - amazon-cloudwatch
  - gatekeeper-system
  - amazon-guardduty

  whitelistedRoles:
  - "admin"
  - "system:*"
  - "eks:*"
  - "cluster-admin"
  - "gatekeeper-manager-role"
  labelSelector:
    matchLabels: {}
    matchExpressions: []
constraints:
  eksallowedcapabilitieseffect:
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
