baselines:
  excludedNamespaces:
  - kube-system
  - amazon-cloudwatch
  - gatekeeper-system
  - amazon-guardduty

  whitelistedRoles:
  - "admin"
  - "system:*"
  - "eks:*"
  - "cluster-admin"
  - "gatekeeper-manager-role"
  - "system:masters"
  - "system:controller:clusterrole-aggregation-controller"
  - "system:controller:expand-controller"
  - "system:controller:generic-garbage-collector"
  - "system:controller:namespace-controller"
  - "system:controller:persistent-volume-binder"
  - "system:kube-controller-manager"

constraints:
  enforcementAction: []

  eksallowedcapabilities:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      allowedCapabilities:
      - "NET_ADMIN"
      - "SYS_TIME"
      requiredDropCapabilities: []

  eksallowedimages:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      allowedRegistries: []
      # requireDigests: true
      allowedPullPolicies:
      - Always
      - IfNotPresent

  eksnoprivilegeescalation:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []

  eksenforceprobes:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      enforceProbes: []

  eksminimisewildcard:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []

  eksblockdefaultnamespace:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedResources: []

  eksblockautomounttoken:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []

  ekscontainernoprivilege:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []

  eksreadonlyfilesystem:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []

  ekslimitsensitiveverbs:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []

  eksenforcesecretaccess:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []

  eksforbiddensysctl:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedSysctls:
      - "net.ipv4.ip_local_port_range"
      - "net.ipv4.tcp_syncookies"
      - "net.ipv4.ping_group_range"
      - "net.core.somaxconn"

  eksmountedsecrets:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedSecrets: []

  eksnetworkpolicyexists:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []

  ekspsphostnamespace:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []

  ekspsphostfilesystem:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedHostPaths:
      - pathPrefix: "/var/log"
        readOnly: true
      - pathPrefix: "/var/lib/kubelet/pods"
        readOnly: true

  eksadminaccess:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      allowedRoles: []

  eksrestrictdefaultsa:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []

  eksresourcelimits:
    version: "1.0.0"
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      defaultCpuLimit: "500m"
      defaultMemoryLimit: "512Mi"
