constraints:
  enforcementAction: "dryrun"

  eksallowedcapabilities:
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      allowedCapabilities: []
      requiredDropCapabilities: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksallowedimages:
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      allowedRegistries: []
      requireDigests: true
      allowedPullPolicies: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksnoprivilegeescalation:
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksenforceprobes:
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      enforceProbes: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksminimisewildcard:
    exemptions:
      excludedNamespaces: []
      whitelistedRoles: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksblockdefaultnamespace:
    exemptions:
      excludedNamespaces: []
      allowedResources: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksblockautomounttoken:
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  ekscontainernoprivilege:
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksreadonlyfilesystem:
    exemptions:
      excludedNamespaces: []
      excludedContainers: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  ekslimitsensitiveverbs:
    exemptions:
      excludedNamespaces: []
      excludedRoles: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksenforcesecretaccess:
    exemptions:
      excludedNamespaces: []
      excludedRoles: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksforbiddensysctl:
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedSysctls: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksmountedsecrets:
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedSecrets: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksnetworkpolicyexists:
    exemptions:
      excludedNamespaces: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  ekspsphostnamespace:
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  ekspsphostfilesystem:
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      allowedHostPaths: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksadminaccess:
    exemptions:
      excludedNamespaces: []
      allowedRoles: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksrestrictdefaultsa:
    exemptions:
      excludedNamespaces: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []

  eksresourcelimits:
    exemptions:
      excludedNamespaces: []
      excludedImages: []
      labelSelector:
        matchLabels: {}
        matchExpressions: []
