constraints:
  enforcementAction: "dryrun" # Default enforcement for development
  exemptions:
    excludedNamespaces: []
    excludedContainers: []
    excludedImages: []
    labelSelector:
      matchLabels: {}
      matchExpressions: []
eksallowedcapabilitieseffect:
  exemptions:
    excludedContainers: []
    excludedImages: []
    allowedCapabilities: []
    requiredDropCapabilities: []
    labelSelector:
      matchLabels: {}
      matchExpressions: []
