constraints:
  enforcementAction: "dryrun" # Default enforcement for development
  exemptions:
    excludedNamespaces: []
    excludedContainers: []
    excludedImages: []
    labelSelector:
      matchLabels: {}


eksallowedcapabilitieseffect:
  exemptions:
    excludedContainers: []
    excludedImages: []
    allowedCapabilities: []
    requiredDropCapabilities: []
    labelSelector:
      matchLabels: {}

eksallowedimageseffect:
  exemptions:
    excludedNamespaces: []
    allowedRegistries: []
    labelSelector:
      matchLabels: {}

eksnoprivilegeescalationeffect:
  exemptions:
    excludedNamespaces: []
    excludedContainers: []
    excludedImages: []
    labelSelector:
      matchLabels: {}

eksenforceprobeseffect:
  exemptions:
    excludedNamespaces: []
    excludedContainers: []
    excludedImages: []
    enforceProbes: []
    labelSelector:
      matchLabels: {}

eksblockwildcardroleseffect:
  exemptions:
    excludedNamespaces: []
    whitelistedRoles: []
    labelSelector:
      matchLabels: {}

eksblockdefaultnamespaceeffect:
  exemptions:
    excludedNamespaces: []
    allowedResources: []
    labelSelector:
      matchLabels: {}
