# customer/customer-1/values.yaml

constraints:
  enforcementAction: "deny"

eksallowedcapabilitieseffect:
  cisBenchmark: "5.2.8, 5.2.9"
  title: "Restrict Container Capabilities"
  type: "container"
  enforces:
  - "Restrict capabilities to reduce container attack surface"
  - "Prevent elevation of privileges"
  remediation:
  - "Review capabilities added to containers"
  - "Drop unneeded capabilities using 'requiredDropCapabilities'"
  - "Follow exemption process if capabilities are required"
  implementation:
  - "Check 'allowedCapabilities' and 'requiredDropCapabilities' in container specs"
  - "Validate capabilities for all containers and initContainers"
  exemptions:
    excludedContainers: []
    excludedImages: []
  labelSelector:
    matchLabels: {}
    matchExpressions: []
  allowedCapabilities: []
  requiredDropCapabilities: []
