# test-deployments/nginx-exempt-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test-exempt
  namespace: customer1-namespace
  labels:
    app: nginx
    environment: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      environment: prod
  template:
    metadata:
      labels:
        app: nginx
        environment: prod
    spec:
      containers:
      - name: customer1-exempt-container
        image: customer1-registry.example.com/trusted/nginx:latest
        securityContext:
          capabilities:
            add:
            - CHOWN
            drop:
            - CAP_SYS_ADMIN
