# test-deployments/nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: dev-namespace
  labels:
    app: nginx
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      environment: dev
  template:
    metadata:
      labels:
        app: nginx
        environment: dev
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        securityContext:
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
